/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCartRouteImport } from './routes/api/cart'
import { Route as ApiCartItemsRouteImport } from './routes/api/cart/items'
import { Route as ApiCartCheckoutRouteImport } from './routes/api/cart/checkout'
import { Route as ApiArticleArticleNumberRouteImport } from './routes/api/article/$articleNumber'
import { Route as ApiCartItemsArticleNumberRouteImport } from './routes/api/cart/items/$articleNumber'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartRoute = ApiCartRouteImport.update({
  id: '/api/cart',
  path: '/api/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartItemsRoute = ApiCartItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => ApiCartRoute,
} as any)
const ApiCartCheckoutRoute = ApiCartCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ApiCartRoute,
} as any)
const ApiArticleArticleNumberRoute = ApiArticleArticleNumberRouteImport.update({
  id: '/api/article/$articleNumber',
  path: '/api/article/$articleNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartItemsArticleNumberRoute =
  ApiCartItemsArticleNumberRouteImport.update({
    id: '/$articleNumber',
    path: '/$articleNumber',
    getParentRoute: () => ApiCartItemsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/health': typeof HealthRoute
  '/api/cart': typeof ApiCartRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/search': typeof ApiSearchRoute
  '/api/session': typeof ApiSessionRoute
  '/api/article/$articleNumber': typeof ApiArticleArticleNumberRoute
  '/api/cart/checkout': typeof ApiCartCheckoutRoute
  '/api/cart/items': typeof ApiCartItemsRouteWithChildren
  '/api/cart/items/$articleNumber': typeof ApiCartItemsArticleNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/health': typeof HealthRoute
  '/api/cart': typeof ApiCartRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/search': typeof ApiSearchRoute
  '/api/session': typeof ApiSessionRoute
  '/api/article/$articleNumber': typeof ApiArticleArticleNumberRoute
  '/api/cart/checkout': typeof ApiCartCheckoutRoute
  '/api/cart/items': typeof ApiCartItemsRouteWithChildren
  '/api/cart/items/$articleNumber': typeof ApiCartItemsArticleNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/health': typeof HealthRoute
  '/api/cart': typeof ApiCartRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/search': typeof ApiSearchRoute
  '/api/session': typeof ApiSessionRoute
  '/api/article/$articleNumber': typeof ApiArticleArticleNumberRoute
  '/api/cart/checkout': typeof ApiCartCheckoutRoute
  '/api/cart/items': typeof ApiCartItemsRouteWithChildren
  '/api/cart/items/$articleNumber': typeof ApiCartItemsArticleNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chat'
    | '/health'
    | '/api/cart'
    | '/api/chat'
    | '/api/orders'
    | '/api/search'
    | '/api/session'
    | '/api/article/$articleNumber'
    | '/api/cart/checkout'
    | '/api/cart/items'
    | '/api/cart/items/$articleNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chat'
    | '/health'
    | '/api/cart'
    | '/api/chat'
    | '/api/orders'
    | '/api/search'
    | '/api/session'
    | '/api/article/$articleNumber'
    | '/api/cart/checkout'
    | '/api/cart/items'
    | '/api/cart/items/$articleNumber'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chat'
    | '/health'
    | '/api/cart'
    | '/api/chat'
    | '/api/orders'
    | '/api/search'
    | '/api/session'
    | '/api/article/$articleNumber'
    | '/api/cart/checkout'
    | '/api/cart/items'
    | '/api/cart/items/$articleNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChatRoute: typeof ChatRoute
  HealthRoute: typeof HealthRoute
  ApiCartRoute: typeof ApiCartRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSessionRoute: typeof ApiSessionRoute
  ApiArticleArticleNumberRoute: typeof ApiArticleArticleNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart': {
      id: '/api/cart'
      path: '/api/cart'
      fullPath: '/api/cart'
      preLoaderRoute: typeof ApiCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/items': {
      id: '/api/cart/items'
      path: '/items'
      fullPath: '/api/cart/items'
      preLoaderRoute: typeof ApiCartItemsRouteImport
      parentRoute: typeof ApiCartRoute
    }
    '/api/cart/checkout': {
      id: '/api/cart/checkout'
      path: '/checkout'
      fullPath: '/api/cart/checkout'
      preLoaderRoute: typeof ApiCartCheckoutRouteImport
      parentRoute: typeof ApiCartRoute
    }
    '/api/article/$articleNumber': {
      id: '/api/article/$articleNumber'
      path: '/api/article/$articleNumber'
      fullPath: '/api/article/$articleNumber'
      preLoaderRoute: typeof ApiArticleArticleNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/items/$articleNumber': {
      id: '/api/cart/items/$articleNumber'
      path: '/$articleNumber'
      fullPath: '/api/cart/items/$articleNumber'
      preLoaderRoute: typeof ApiCartItemsArticleNumberRouteImport
      parentRoute: typeof ApiCartItemsRoute
    }
  }
}

interface ApiCartItemsRouteChildren {
  ApiCartItemsArticleNumberRoute: typeof ApiCartItemsArticleNumberRoute
}

const ApiCartItemsRouteChildren: ApiCartItemsRouteChildren = {
  ApiCartItemsArticleNumberRoute: ApiCartItemsArticleNumberRoute,
}

const ApiCartItemsRouteWithChildren = ApiCartItemsRoute._addFileChildren(
  ApiCartItemsRouteChildren,
)

interface ApiCartRouteChildren {
  ApiCartCheckoutRoute: typeof ApiCartCheckoutRoute
  ApiCartItemsRoute: typeof ApiCartItemsRouteWithChildren
}

const ApiCartRouteChildren: ApiCartRouteChildren = {
  ApiCartCheckoutRoute: ApiCartCheckoutRoute,
  ApiCartItemsRoute: ApiCartItemsRouteWithChildren,
}

const ApiCartRouteWithChildren =
  ApiCartRoute._addFileChildren(ApiCartRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChatRoute: ChatRoute,
  HealthRoute: HealthRoute,
  ApiCartRoute: ApiCartRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSessionRoute: ApiSessionRoute,
  ApiArticleArticleNumberRoute: ApiArticleArticleNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
